# Generated by Django 6.0.6 on 2026-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External URL for image'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hiringpartner',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='External URL for logo (S3, CDN, etc.)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='hiringpartner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='partners/'),
        ),
    ]
