# Generated by Django 6.0.6 on 2026-07-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_image_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='career_guidance_icon',
            field=models.ImageField(blank=True, help_text='Icon for Career Guidance feature', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='excel_banner',
            field=models.ImageField(blank=True, help_text='Banner image below the feature grid', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='interview_prep_icon',
            field=models.ImageField(blank=True, help_text='Icon for Interview Preparation feature', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='materials_icon',
            field=models.ImageField(blank=True, help_text='Icon for Study Materials feature', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='placement_icon',
            field=models.ImageField(blank=True, help_text='Icon for Placement Assistance feature', upload_to='home/'),
        ),
    ]
