# Generated by Django 6.0.6 on 2026-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_career_guidance_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='nutshell_1',
            field=models.ImageField(blank=True, help_text='Icon for Technical Seminars', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nutshell_2',
            field=models.ImageField(blank=True, help_text='Icon for Resume Preparation', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nutshell_3',
            field=models.ImageField(blank=True, help_text='Icon for Mock Interviews', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nutshell_4',
            field=models.ImageField(blank=True, help_text='Icon for Placement Assistance', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nutshell_5',
            field=models.ImageField(blank=True, help_text='Icon for Internship', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nutshell_6',
            field=models.ImageField(blank=True, help_text='Icon for Real-time Projects', upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nutshell_illustration',
            field=models.ImageField(blank=True, help_text='Large illustration for Career Services section', upload_to='home/'),
        ),
    ]
