# Generated by Django 6.0.6 on 2026-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_coursebrochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('course', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('intern_image', models.ImageField(blank=True, upload_to='internships/interns/')),
                ('intern_image_url', models.URLField(blank=True, default='')),
                ('company_logo', models.ImageField(blank=True, upload_to='internships/companies/')),
                ('company_logo_url', models.URLField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Internships',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('tech_stack', models.CharField(blank=True, default='', max_length=200)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='live_projects/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Live Projects',
                'ordering': ['order'],
            },
        ),
    ]
